INSERT INTO Naves (ID, NOMBRE, FECHA_ALTA, FECHA_MODIF, FECHA_BAJA) VALUES (1, 'Eslave I', NULL, NULL, NULL);

INSERT INTO Naves (ID, NOMBRE, FECHA_ALTA, FECHA_MODIF, FECHA_BAJA) VALUES (2, 'Millennium Falcon', NULL, NULL, NULL);